services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=1234
    ports:
      - "15672:15672"
      - "5672:5672"
  auction-svc:
    image: hzd454/auction-service:latest
    build:
      context: .
      dockerfile: src/AuctionService/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=postgres;Password=1234;Database=db
      - IdentityServiceUrl=http://identity-svc
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "7001:80"

volumes:
  pgdata:
  mongodata:
