services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=1234
    ports:
      - "15672:15672"
      - "5672:5672"
  auction-svc:
    image: hzd454/auction-service:latest
    build:
      context: .
      dockerfile: src/AuctionService/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=postgres;Password=1234;Database=db
      - IdentityServiceUrl=http://identity-svc
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "7001:80"
  search-svc:
    image: hzd454/search-service:latest
    build:
      context: .
      dockerfile: src/SearchService/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=mongodb://root:1234@mongodb:27017
      - IdentityServiceUrl=http://identity-svc
      - AuctionServiceUrl=http://auction-svc
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - "7002:80"
  identity-svc:
    image: hzd454/identity-service:latest
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=postgres;Password=1234;Database=identity
    depends_on:
      - postgres
    ports:
      - "5001:80"
  gateway-svc:
    image: hzd454/gatway-service:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "6001:80"
volumes:
  pgdata:
  mongodata:
